config/routes.rb
Rails.application.routes.draw do

  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	
	def new

	end

	def create
		@product =  Product.new(product_params)
		if @product.save
			redirect_to action: 'index'
		else
			render :action => 'new'
		end
	end

	def show
		@article = Product.find(params[:id])
	end

	def index
		@products = Product.all
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])

		if @product.update(product_params)
			redirect_to :action => "index"
		else
			render 'edit'
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to :action => 'index'
	end

	private
		def product_params
			params.require(:product).permit(:name, :price)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Market</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= form_for :product, url: product_path(@product), method: :patch do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :price %><br>
		<%= f.text_field :price %>
	</p>
	
	<p>
		<%= f.submit "Edit Product" %>
	</p>
<% end %>

app/views/products/index.html.erb
<h1>Products</h1>
<% @products.each do |product| %>
	<p>
		<b><%= product.name %></b><br>
		Price: Rs.<%= product.price  %> |
		<%= link_to "Edit", edit_product_path(product) %> |
		<%= link_to "Delete", product_path(product), method: :delete, data: { confirm: "Are you sure you want to delete?" } %>
	</p>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_for :product, url: products_path do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :price %><br>
		<%= f.text_field :price %>
	</p>
	
	<p>
		<%= f.submit "Create Product" %>
	</p>
<% end %>

app/views/products/show.html.erb
<%= @article.name %><br>
<%= @article.price %>